{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sportzinteractive",
    "module": "si-live-sdk",
    "version": "1.0.0-beta6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "si-live-sdk-1.0.0-beta6.aar",
          "url": "si-live-sdk-1.0.0-beta6.aar",
          "size": 405085,
          "sha512": "f034711111994208994e28cc8859841bfbf5759b96f183c35827f57ef7371805a14a7e213459a69c3f07627eac75c142acde34d8e2746cc8dc4a49f0de0fe98a",
          "sha256": "276972c25c8fdcf9db7c932fd468002acd1105d082381d6ba7f1dcc361d696f1",
          "sha1": "c327c8d434f097b41c40766ce705a3920a90b1a1",
          "md5": "f1506309235cd5eb5a1e4701d094438f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.brightcove.player",
          "module": "exoplayer2",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "si-live-sdk-1.0.0-beta6.aar",
          "url": "si-live-sdk-1.0.0-beta6.aar",
          "size": 405085,
          "sha512": "f034711111994208994e28cc8859841bfbf5759b96f183c35827f57ef7371805a14a7e213459a69c3f07627eac75c142acde34d8e2746cc8dc4a49f0de0fe98a",
          "sha256": "276972c25c8fdcf9db7c932fd468002acd1105d082381d6ba7f1dcc361d696f1",
          "sha1": "c327c8d434f097b41c40766ce705a3920a90b1a1",
          "md5": "f1506309235cd5eb5a1e4701d094438f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "si-live-sdk-1.0.0-beta6-sources.jar",
          "url": "si-live-sdk-1.0.0-beta6-sources.jar",
          "size": 177657,
          "sha512": "d60442f7d2818d3ab2f4cabff436993f0ebf3339b12a609bbff724d99335d38f08112ae6399215f706168c63db243fcb37b992e6a4ed1918bedd69ce4dd50a36",
          "sha256": "5b4323d43fc82ce35ed8c04a7b2a63a54ae322db5852643e3948fd4bde05fd9f",
          "sha1": "5cb9708e426984485ae319b2eff0f2ce658bf73d",
          "md5": "5ad87a7aebaa3987fb34ecaaec8f4a47"
        }
      ]
    }
  ]
}
